// P3 lifecycle failures written before P3 implementation. Fake DOM/clock only.
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import {makeWorkloadReview} from '../workload-review.js';
const cases=[];async function check(name,fn){try{await fn();cases.push({name,passed:true});}catch(error){cases.push({name,passed:false,error:String(error)});}}
const flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
function fixture({cap=60,remaining=45,ready=true}={}){
 const dom=new JSDOM('<body><canvas></canvas></body>',{url:'http://fixture.invalid/?workloadReview=1&desktopTier=pace&desktopTrial=1'}),names=['document','location','navigator','addEventListener','fetch','performance','setTimeout','clearTimeout','AbortController'],old=new Map(names.map(n=>[n,Object.getOwnPropertyDescriptor(globalThis,n)]));
 const install=(n,value)=>Object.defineProperty(globalThis,n,{value,configurable:true,writable:true});let now=0,serial=0,active=0,paused=true,submissions=0,route=false,starts=0,cancels=0,reads=0,setTimes=0,readbacks=0;const timers=new Map(),records=[];
 install('document',dom.window.document);install('location',dom.window.location);install('navigator',dom.window.navigator);install('addEventListener',dom.window.addEventListener.bind(dom.window));install('performance',{now:()=>now});install('AbortController',dom.window.AbortController);
 install('setTimeout',(fn,ms)=>{const id=++serial;timers.set(id,{fn,at:now+ms});return id;});install('clearTimeout',id=>timers.delete(id));install('fetch',async(_url,options)=>{records.push(JSON.parse(options.body));return{ok:true,status:200};});
 const canvas=document.querySelector('canvas');canvas.toDataURL=()=>{readbacks++;throw Error('P3 must not screenshot');};const renderer={render(){},shadowMap:{render(){}},domElement:canvas,info:{render:{calls:0,triangles:0}},getContext(){throw Error('P3 must not query GL');}};
 const api=makeWorkloadReview(renderer,new URLSearchParams(location.search));
 let flags={};const observation=()=>({routeActive:route,recording:false,videoPending:false,pendingCapture:false,evidenceReadback:false,...flags});
 const state=()=>{reads++;return{build:{sourceHash:'source',assetsHash:'assets'},drawSize:[1280,720],viewport:[1280,720],pixelRatio:1,effectivePixelRatio:1,quality:'high',fov:62,exposure:1.35,adaptive:false,worldTime:60+active,position:[active*1.55,1.75,0],quaternion:[0,0,0,1],programErrors:0,workload:{targetFps:cap,maxPixels:921600,maxDimension:1280,fixed:false,desktopTier:'pace',deadlineSeconds:45,overrideDeadlineRemaining:remaining-active,bootComplete:true,activeSeconds:active,pausedSeconds:0,submittedFrames:submissions,paused},skyCache:{ready,width:1536,height:384,steps:120,raysPerFrame:12288,frozen:false},vegetation:{pending:false,error:null,treeWindTime:{override:null}},terrain:{pending:false,revision:1,reflection:{mode:'fixed-proxy'}},flow:{pending:false,error:null,composition:{mode:'linear-hdr'},diagnostic:{reflectionFrozen:false,aoDisabled:false,cheapWater:false}},resources:[],navigation:{groundRoute:route,speed:1.55,constraints:{blocked:null}},route:route?{id:'side-spring-loop',clock:'wall',clip:true,durationSeconds:25,progress:active/225}:null,benchmarkObservation:observation(),memory:{},drawCalls:10,triangles:100};};
 const context={getState:state,getPaused:()=>paused,setPaused:v=>{paused=v;},externalBusy:()=>false,benchmark:{get active(){return route},get observationState(){return observation()},startRealtime(opts){starts++;assert.deepEqual(opts,{capture:false,seconds:25,clip:true,timing:true,prefixMetres:38.75});route=true;return true;},cancel(){cancels++;route=false;}},sky:{status:()=>({ready}),setFrozen(){}},landscape:{setReflectionTerrain(){},setReflectionTiles(){}},props:{setDiagnosticGrass(){}},water:{setDiagnostic(){},setReflectionRegion(){}},setAtlasNormalDeferred(){},setPixelScale(){},setTime(){setTimes++;}};api.attach(context);
 async function frame(ms=1000/60){now+=ms;if(!paused)active+=ms/1000;submissions++;api.beginFrame(now,ms);api.endFrame(2);for(const[id,t]of[...timers])if(t.at<=now){timers.delete(id);t.fn();}await flush();}
 async function click(){const b=document.querySelector('#gpu-motion');assert(b,'P3 button exists');const pending=b.onclick();await flush();for(const[id,t]of[...timers])if(t.at<=now){timers.delete(id);t.fn();}await flush();await pending;}
 function close(){dom.window.close();for(const[n,d]of old)d?Object.defineProperty(globalThis,n,d):delete globalThis[n];}
 return{api,context,click,frame,records,close,flags,counts:()=>({starts,cancels,reads,setTimes,readbacks}),pause:()=>{paused=true;api.event('pause-state',{paused:true});}};
}
for(const [name,config]of [['30 cap',{cap:30}],['insufficient bounded trial',{remaining:20}],['not ready',{ready:false}]])await check(name+' does not start route and records failed eligibility',async()=>{const f=fixture(config);try{await f.click();assert.equal(f.counts().starts,0);assert.equal(f.records.at(-1).passed,false);}finally{f.close();}});
await check('12 warm + 12 sample with no restart/no readback/no setTime saves lowFPS valid failure',async()=>{const f=fixture();try{await f.click();for(let i=0;i<600;i++)await f.frame(40);const r=f.records.find(r=>r.kind==='motion-timing');assert(r);assert.equal(r.validation.valid,true);assert.equal(r.performance.passed,false);assert.equal(r.passed,false);assert.equal(f.counts().starts,1);assert.equal(f.counts().setTimes,0);assert.equal(f.counts().readbacks,0);assert.equal(f.api.collecting,false);}finally{f.close();}});
await check('pause during warmup saves incomplete and releases route',async()=>{const f=fixture();try{await f.click();await f.frame();f.pause();await flush();assert.equal(f.records.at(-1).completed,false);assert.equal(f.api.collecting,false);assert.equal(f.counts().cancels,1);}finally{f.close();}});
await check('capture during sample cancels instead of hiding its frames',async()=>{const f=fixture();try{await f.click();for(let i=0;i<305;i++)await f.frame(40);f.flags.recording=true;await f.frame(40);assert.equal(f.records.at(-1).completed,false);}finally{f.close();}});
await check('context loss saves last safe state without reading more state',async()=>{const f=fixture();try{await f.click();await f.frame();const n=f.counts().reads;await f.api.contextLost({test:true});assert.equal(f.counts().reads,n);assert(f.records.some(r=>r.kind==='motion-timing'&&r.completed===false));}finally{f.close();}});
await check('timing option preserves default API and owns timing clip pause',()=>{const s=readFileSync(new URL('../benchmark.js',import.meta.url),'utf8');assert.match(s,/startRealtime\(\{[^\n]*timing=false/);assert.match(s,/evidenceMode=video\?'video':timing\?'timing':'normal'/);assert.match(s,/if\(\(replay\.clip\|\|hadCapture\)&&evidenceMode!=='timing'\)pauseScene\(\)/);});
const result={schema:'island-motion-harness-offline-v1',scope:'prewritten fake DOM/clock lifecycle checks, no browser/GPU',cases,passed:cases.every(c=>c.passed)};if(process.argv[2]){mkdirSync(dirname(resolve(process.argv[2])),{recursive:true});writeFileSync(process.argv[2],JSON.stringify(result,null,2)+'\n');}console.log(JSON.stringify(result));if(!result.passed)process.exitCode=1;
