import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import * as T from 'three';
const cases=[];function check(name,fn){try{fn();cases.push({name,passed:true});}catch(e){cases.push({name,passed:false,error:String(e.message)});}}
let module;try{module=await import('../near-shadow.js');}catch(e){cases.push({name:'module exists after failure inventory',passed:false,error:String(e.message)});}
if(module){
 const {makeNearShadow,patchNearShadowLighting,nearShadowWeight,nearShadowVisibility,nearShadowConfig}=module;
 const fixture=()=>{const scene=new T.Scene(),sun=new T.DirectionalLight(0xffffff,2.35);sun.castShadow=true;sun.position.set(200,500,300);sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-140,right:140,top:140,bottom:-140,near:1,far:1200});sun.shadow.bias=-.00015;sun.shadow.normalBias=.08;sun.shadow.radius=1.5;scene.add(sun,sun.target);return{scene,sun,camera:new T.PerspectiveCamera()};};
 check('default off is invisible, zero energy, unallocated and primary unchanged',()=>{const {scene,sun}=fixture(),before=[sun.shadow.camera.left,sun.shadow.camera.right,sun.shadow.mapSize.x],n=makeNearShadow({scene,sun});assert.equal(n.light.intensity,0);assert.equal(n.light.visible,false);assert.equal(n.light.castShadow,true);assert.deepEqual(n.resources(),[]);assert.equal(n.status().expectedAdditionalShadowPasses,0);assert.deepEqual(before,[sun.shadow.camera.left,sun.shadow.camera.right,sun.shadow.mapSize.x]);n.dispose();});
 check('validated cast-shadow ordering ignores non-shadow directional lights',()=>{const {scene,sun}=fixture();scene.add(new T.DirectionalLight());const n=makeNearShadow({scene,sun});n.setEnabled(true);assert.deepEqual(n.status().indices,{primary:0,near:1});assert.equal(n.light.shadow.mapSize.x,1024);assert.equal(n.status().plannedAttachmentBytes,8388608);n.dispose();});
 check('unexpected shadow directionals fail enable rather than sampling wrong map',()=>{const {scene,sun}=fixture(),extra=new T.DirectionalLight();extra.castShadow=true;scene.add(extra);const n=makeNearShadow({scene,sun});assert.throws(()=>n.setEnabled(true),/directional|order/i);assert.equal(n.light.visible,false);n.dispose();});
 check('projection is64m snapped independent of camera rotation and jitter',()=>{const {scene,sun,camera}=fixture(),n=makeNearShadow({scene,sun,enabled:true});camera.position.set(1.234,5,3.456);n.update(camera,()=>2);const a=n.status();assert.equal(a.texelMetres,.0625);assert.ok(a.gridError.every(x=>x<1e-8));const p=n.light.position.clone();camera.rotation.set(.7,1.2,0);camera.projectionMatrix.elements[8]+=.001;n.update(camera,()=>2);assert.deepEqual(n.light.position.toArray(),p.toArray());assert.deepEqual([n.light.shadow.camera.left,n.light.shadow.camera.right],[-32,32]);n.dispose();});
 check('sun direction follows primary while bias scales with actual primary texel',()=>{const {scene,sun,camera}=fixture(),n=makeNearShadow({scene,sun,enabled:true});n.update(camera,()=>0);const ratio=.0625/(280/2048);assert.ok(Math.abs(n.light.shadow.bias-sun.shadow.bias*ratio)<1e-14);assert.ok(Math.abs(n.light.shadow.normalBias-.08*ratio)<1e-14);sun.position.set(-300,600,100);n.update(camera,()=>0);const a=sun.position.clone().sub(sun.target.position).normalize(),b=n.light.position.clone().sub(n.light.target.position).normalize();assert.ok(a.distanceTo(b)<1e-12);sun.shadow.mapSize.set(512,512);n.update(camera,()=>0);assert.ok(Math.abs(n.status().biasScale-.0625/(280/512))<1e-12);n.dispose();});
 check('invalid update does not poison previous projection',()=>{const {scene,sun,camera}=fixture(),n=makeNearShadow({scene,sun,enabled:true});n.update(camera,()=>0);const a=n.light.position.toArray();assert.throws(()=>n.update(camera,()=>NaN),/height/i);assert.deepEqual(n.light.position.toArray(),a);n.dispose();});
 check('light-plane mask guards depth and continuously feathers20to30metres',()=>{assert.equal(nearShadowWeight([.5,.5,.5]),1);assert.equal(nearShadowWeight([.8125,.5,.5]),1);assert.equal(nearShadowWeight([.96875,.5,.5]),0);assert.equal(nearShadowWeight([.5,.5,-.01]),0);assert.equal(nearShadowWeight([.5,.5,1.01]),0);let previous=1;for(let i=0;i<=100;i++){const w=nearShadowWeight([.8125+.15625*i/100,.5,.5]);assert.ok(w<=previous&&Math.abs(w-previous)<.02);previous=w;}});
 check('raw near mixes once with prior primary/cache result and intensity',()=>{for(const far of [.28,.7,1])for(const raw of [0,.2,1])for(const w of [0,.5,1]){const v=nearShadowVisibility({far,raw,weight:w,intensity:.8});assert.equal(v,far*(1-w)+(1+(raw-1)*.8)*w);assert.ok(v>=Math.min(far,1+(raw-1)*.8)-1e-12);}});
 check('shader patch preserves other loops and makes exactly five raw queries',()=>{const chunk=T.ShaderChunk.lights_fragment_begin,out=patchNearShadowLighting(chunk),a=chunk.indexOf('#if ( NUM_DIR_LIGHTS > 0 )'),b=chunk.indexOf('#if ( NUM_RECT_AREA_LIGHTS > 0 )');assert.equal(out.slice(0,a),chunk.slice(0,a));assert.ok(out.endsWith(chunk.slice(b)));assert.equal((out.match(/texture\( directionalShadowMap\[ 1 \]/g)||[]).length,5);assert.equal((out.match(/getShadow\(/g)||[]).length,(chunk.match(/getShadow\(/g)||[]).length);assert.doesNotMatch(out,/getShadow\( directionalShadowMap\[ 1 \]/);assert.match(out,/UNROLLED_LOOP_INDEX == 0/);assert.match(out,/UNROLLED_LOOP_INDEX != 1/);assert.match(out,/mix\( primaryVisibility, nearVisibility, nearWeight \)/);assert.doesNotMatch(out,/canopyLighting|islandShadowVisibility/);assert.match(out,/nearCoord\.z >= 0\./);assert.throws(()=>patchNearShadowLighting('bad'),/directional/i);});
 check('native sorting and loop assumptions are explicitly pinned',()=>{const source=readFileSync(new URL('../../../node_modules/three/src/renderers/webgl/WebGLLights.js',import.meta.url),'utf8');assert.match(source,/lightB\.castShadow \? 2 : 0/);assert.match(source,/lights\.sort\( shadowCastingAndTexturingLightsFirst \)/);assert.equal(nearShadowConfig.comparisonCalls,5);});
 check('cached allocation survives off and disposal removes both light and target',()=>{const {scene,sun}=fixture(),n=makeNearShadow({scene,sun,enabled:true});let disposed=0;n.light.shadow.map={width:1024,height:1024,dispose(){disposed++;}};n.setEnabled(false);assert.equal(n.resources().length,1);assert.equal(n.status().estimatedResidentAttachmentBytes,8388608);const light=n.light,target=light.target;n.dispose();n.dispose();assert.equal(disposed,1);assert.equal(scene.children.includes(light),false);assert.equal(scene.children.includes(target),false);assert.throws(()=>n.update(new T.PerspectiveCamera(),()=>0),/disposed/i);});
}
const result={schema:'near-shadow-offline-v1',scope:'prewritten projection/order/shader-source contracts; no GPU compile or visual proof',cases,passed:cases.length>1&&cases.every(c=>c.passed)};if(process.argv[2]){const p=resolve(process.argv[2]);mkdirSync(dirname(p),{recursive:true});writeFileSync(p,JSON.stringify(result,null,2)+'\n');}console.log(JSON.stringify(result));if(!result.passed)process.exitCode=1;
