// Pre-implementation inventory above. Small deterministic geometry oracle only.
import assert from 'node:assert/strict';import {writeFileSync,mkdirSync} from 'node:fs';import {dirname,resolve} from 'node:path';
const cases=[];let api;try{api=await import('../reflection-tiles.js');}catch(error){cases.push({name:'tile implementation available',passed:false,error:String(error)});}
const check=(name,fn)=>{try{fn();cases.push({name,passed:true});}catch(error){cases.push({name,passed:false,error:String(error)});}};
if(api){const {buildReflectionTiles}=api,p=new Float32Array([-800,-8,-500,-100,-7,-500,-800,-9,100, 10,5,10,1000,3,10,10,7,1000, 520,0,520,521,0,520,520,0,521]),ix=new Uint32Array([3,4,5,0,1,2,6,7,8]);
 check('every input triangle appears exactly once with winding and input arrays unchanged',()=>{const a=ix.slice(),b=p.slice(),cells=buildReflectionTiles(ix,p);const triples=v=>Array.from({length:v.length/3},(_,i)=>Array.from(v.slice(i*3,i*3+3)).join(',')).sort(),all=new Uint32Array(cells.reduce((n,c)=>n+c.indices.length,0));let o=0;for(const c of cells){all.set(c.indices,o);o+=c.indices.length;}assert.deepEqual(triples(all),triples(ix));assert.deepEqual(ix,a);assert.deepEqual(p,b);assert.ok(cells.length>1);});
 check('actual bounds include all protruding vertices across nominal tile borders',()=>{const cells=buildReflectionTiles(ix,p);for(const c of cells)for(const k of c.indices)for(let a=0;a<3;a++)assert.ok(p[k*3+a]>=c.bounds[a]&&p[k*3+a]<=c.bounds[a+3]);assert.ok(cells.some(c=>c.bounds[3]-c.bounds[0]>512));});
 check('height ranges remain conservative and monotonic within each tile',()=>{for(const c of buildReflectionTiles(ix,p)){let prev=-Infinity;for(let i=0;i<c.indices.length;i+=3){const h=Math.ceil(Math.max(...Array.from(c.indices.slice(i,i+3),k=>p[k*3+1])));assert.ok(h>=prev);prev=h;}assert.equal(c.range.starts.at(-1),c.indices.length);assert.equal(c.range.indices,c.indices);}});
 check('index supported type is retained',()=>{assert.ok(buildReflectionTiles(new Uint16Array(ix),p).every(c=>c.indices instanceof Uint16Array));});
 check('malformed and extreme inputs select the bounded fallback',()=>{for(const [a,b]of [[new Uint32Array([0,1]),p],[new Uint32Array([99,1,2]),p],[ix,new Float32Array([NaN,0,0])],[new Uint32Array([0,1,2]),new Float32Array([1e20,0,0,0,1e9,0,0,0,1])]])assert.equal(buildReflectionTiles(a,b),null);});
 check('empty input does not create a phantom mesh',()=>{assert.deepEqual(buildReflectionTiles(new Uint32Array(),new Float32Array()),[]);});
 check('independent seeded membership, bounds and range oracle over many tiles',()=>{let seed=1;const rand=()=>((seed=(seed*1664525+1013904223)>>>0)/2**32),p=[],ix=[];for(let i=0;i<2100;i++){p.push(rand()*3000-1500,rand()*90-45,rand()*3000-1500);ix.push(i);}const pos=new Float32Array(p),cells=buildReflectionTiles(new Uint32Array(ix),pos),seen=new Set();for(const c of cells)for(let i=0;i<c.indices.length;i+=3){assert.ok(!seen.has(c.indices[i]));seen.add(c.indices[i]);for(let j=0;j<3;j++)for(let a=0;a<3;a++)assert.ok(pos[c.indices[i+j]*3+a]>=c.bounds[a]&&pos[c.indices[i+j]*3+a]<=c.bounds[a+3]);}assert.equal(seen.size,700);});
}
const result={schema:'island-reflection-tiles-offline-v1',scope:'CPU index membership/bounds/range; no GL or FPS claim',cases,passed:cases.length>1&&cases.every(c=>c.passed)};
if(process.argv[2]){const p=resolve(process.argv[2]);mkdirSync(dirname(p),{recursive:true});writeFileSync(p,JSON.stringify(result,null,2)+'\n');}console.log(JSON.stringify({passed:result.passed,cases:cases.length,failed:cases.filter(c=>!c.passed)}));if(!result.passed)process.exitCode=1;
