// Failure inventory written before the regional follower implementation:
// corner chords, navigation catchup, paused movement, unsafe pose assignment,
// new obstacles ignored, and time/video falsely accepted as route completion.
import assert from 'node:assert/strict';import * as T from 'three';
import {writeFileSync,mkdirSync} from 'node:fs';import {dirname,resolve} from 'node:path';
import {makeGroundNavigation} from '../ground-navigation.js';
import {makeRegionalFollower} from '../regional-follow.js';
const cases=[];function check(name,fn){try{fn();cases.push({name,passed:true});}catch(error){cases.push({name,passed:false,error:String(error)});}}
function fixture(points,heightAt=()=>0,rockAt=()=>false){const nav=makeGroundNavigation({heightAt,rockAt,waterAt:()=>-100,animal:{constrain:()=>false}}),position=new T.Vector3(points[0][0],heightAt(...points[0])+1.75,points[0][1]);let calls=0,maxStep=0;const follower=makeRegionalFollower(points,(p,previous,d)=>{calls++;maxStep=Math.max(maxStep,d);return nav.move(p,previous,d);});return {position,follower,counts:()=>({calls,maxStep})};}
check('walk the verified edges of a sharp corner without a steeper diagonal chord',()=>{const f=fixture([[0,0],[1,0],[1,1]],(x,z)=>.65*(x+z));for(let i=0;i<100&&!f.follower.status().complete;i++){const s=f.follower.advance(f.position,1/30);assert.equal(s.blocked,null);}assert.equal(f.follower.status().complete,true);assert.ok(Math.hypot(f.position.x-1,f.position.z-1)<1e-6);assert.ok(Math.abs(f.follower.status().distance-2)<1e-6);assert.ok(f.counts().calls>30);assert.ok(f.counts().maxStep<=.050001);});
check('discard late navigation time instead of traversing the accumulated distance',()=>{const f=fixture([[0,0],[100,0]]);f.follower.advance(f.position,3);assert.ok(Math.abs(f.position.x-.155)<1e-6);f.follower.advance(f.position,1/30);assert.ok(Math.abs(f.position.x-(.155+1.55/30))<1e-6);assert.equal(f.follower.status().complete,false);});
check('zero, negative or invalid pause delta does not move or probe',()=>{const f=fixture([[0,0],[1,0]]);for(const dt of [0,-1,NaN,Infinity])f.follower.advance(f.position,dt);assert.equal(f.position.x,0);assert.equal(f.counts().calls,0);assert.equal(f.follower.status().distance,0);});
check('new ordinary collision obstacles stop advancement without jumping over them',()=>{const f=fixture([[0,0],[3,0]],()=>0,x=>x>.2);let result;for(let i=0;i<20;i++){result=f.follower.advance(f.position,1/30);if(result.blocked)break;}assert.equal(result.blocked,'rock');assert.ok(f.position.x<=.200001);assert.equal(result.complete,false);});
check('a closed loop finishes at the actual ground start with all segments walked',()=>{const f=fixture([[0,0],[1,0],[1,1],[0,0]],x=>x*.2);for(let i=0;i<200&&!f.follower.status().complete;i++)assert.equal(f.follower.advance(f.position,1/60).blocked,null);const s=f.follower.status();assert.equal(s.complete,true);assert.ok(Math.hypot(f.position.x,f.position.z)<1e-6);assert.ok(Math.abs(s.distance-(2+Math.SQRT2))<1e-6);assert.ok(Math.abs(f.position.y-1.75)<1e-6);});
const result={schema:'island-regional-follow-offline-v1',scope:'CPU fixture terrain; not actual museum motion or GPU acceptance',cases,passed:cases.every(x=>x.passed)};
if(process.argv[2]){const p=resolve(process.argv[2]);mkdirSync(dirname(p),{recursive:true});writeFileSync(p,JSON.stringify(result,null,2)+'\n');}console.log(JSON.stringify({passed:result.passed,cases:cases.length,failed:cases.filter(x=>!x.passed)}));if(!result.passed)process.exitCode=1;
