// Failure cases and checks written before the bounded recorder implementation.
// CPU/DOM only; no browser, GPU, capture device or network is started.
import assert from 'node:assert/strict';
import {writeFileSync,mkdirSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import {JSDOM} from 'jsdom';
import * as T from 'three';
import {makeReviewRecorder} from '../review-recorder.js';
import {makeBenchmark} from '../benchmark.js';
const cases=[];
async function check(name,fn){try{await fn();cases.push({name,passed:true});}catch(error){cases.push({name,passed:false,error:String(error),stack:error.stack});}}
const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
function recorderFixture({throws=false,noStop=false,upload=null,mime='video/webm',empty=false}={}){
 let time=0,seq=0,streams=0,tracks=0,creates=0,uploads=0,publishes=0;const timers=new Map(),instances=[],stops=[];
 class Recorder{static isTypeSupported(t){return t===mime;}constructor(){if(throws)throw Error('encoder unavailable');creates++;this.mimeType=mime;this.state='inactive';instances.push(this);}start(){this.state='recording';}pause(){this.state='paused';}resume(){this.state='recording';}stop(){this.state='inactive';if(noStop)return;if(!empty)this.ondataavailable?.({data:new Blob(['encoded-frame'],{type:mime})});this.onstop?.();}}
 const controller=makeReviewRecorder({canvas:{captureStream(){streams++;return {getTracks:()=>[{stop(){tracks++;}}]};}},Recorder,now:()=>time,setTimer:(f,ms)=>{const id=++seq;timers.set(id,{f,at:time+ms});return id;},clearTimer:id=>timers.delete(id),upload:async(blob,signal)=>{uploads++;return upload?upload(blob,signal):'/capture.'+(mime==='video/mp4'?'mp4':'webm');},publish:()=>publishes++,onStop:reason=>stops.push(reason)});
 const advance=async(ms)=>{time+=ms;for(const [id,t]of [...timers])if(t.at<=time){timers.delete(id);t.f();}await flush();};
 return {controller,advance,instances,stops,counts:()=>({streams,tracks,creates,uploads,publishes,timers:timers.size})};
}
await check('arming does not construct a recorder or capture stream',()=>{const f=recorderFixture();assert.equal(f.controller.arm(),true);assert.equal(f.controller.state.status,'armed');assert.deepEqual(f.counts(),{streams:0,tracks:0,creates:0,uploads:0,publishes:0,timers:1});});
await check('cancel before any actual frame is empty and never uploaded',async()=>{const f=recorderFixture();f.controller.arm();f.controller.stop('window-blur');await flush();assert.equal(f.controller.state.status,'empty');assert.equal(f.controller.state.pending,false);assert.equal(f.counts().uploads,0);assert.equal(f.counts().streams,0);});
await check('first actual frame starts recording and duplicate arm is rejected',()=>{const f=recorderFixture();f.controller.arm();f.controller.afterFrame();assert.equal(f.controller.state.status,'recording');assert.equal(f.controller.state.frames,1);assert.equal(f.controller.arm(),false);assert.equal(f.counts().creates,1);});
await check('pause prevents frame counting and can resume only existing session',()=>{const f=recorderFixture();f.controller.arm();f.controller.setPaused(true);f.controller.afterFrame();assert.equal(f.counts().creates,0);f.controller.setPaused(false);f.controller.afterFrame();f.controller.setPaused(true);f.controller.afterFrame();assert.equal(f.controller.state.frames,1);assert.equal(f.instances[0].state,'paused');f.controller.setPaused(false);f.controller.afterFrame();assert.equal(f.controller.state.frames,2);});
await check('nonempty completion releases tracks, uploads once and publishes',async()=>{const f=recorderFixture();f.controller.arm();f.controller.afterFrame();f.controller.afterFrame();f.controller.stop('clip complete');await flush();assert.equal(f.controller.state.status,'saved');assert.equal(f.controller.state.pending,false);assert.equal(f.counts().tracks,1);assert.equal(f.counts().uploads,1);assert.equal(f.counts().publishes,1);assert.ok(f.controller.state.bytes>0);});
await check('empty encoder result is retained and is not POSTed',async()=>{const f=recorderFixture({empty:true});f.controller.arm();f.controller.afterFrame();f.controller.stop('clip complete');await flush();assert.equal(f.controller.state.status,'empty');assert.equal(f.counts().uploads,0);assert.equal(f.counts().publishes,0);assert.equal(f.counts().tracks,1);});
await check('encoder construction failure cleans stream and asks scene to stop',async()=>{const f=recorderFixture({throws:true});f.controller.arm();f.controller.afterFrame();await flush();assert.equal(f.controller.state.pending,false);assert.match(f.controller.state.saveError,/encoder unavailable/);assert.equal(f.counts().tracks,1);assert.equal(f.stops.length,1);});
await check('wall deadline applies even while armed/paused',async()=>{const f=recorderFixture();f.controller.arm({wallLimitMs:20000});f.controller.setPaused(true);await f.advance(20000);assert.equal(f.controller.state.pending,false);assert.equal(f.stops[0],'capture wall deadline');assert.equal(f.counts().streams,0);});
await check('missing encoder stop event has bounded cleanup',async()=>{const f=recorderFixture({noStop:true});f.controller.arm();f.controller.afterFrame();f.controller.stop('user stopped');await f.advance(3000);assert.equal(f.controller.state.pending,false);assert.equal(f.counts().tracks,1);assert.match(f.controller.state.saveError,/stop timeout/);});
await check('upload timeout clears pending and aborts without destroying preview',async()=>{let signal;const f=recorderFixture({upload:(_,s)=>{signal=s;return new Promise(()=>{});}});f.controller.arm();f.controller.afterFrame();f.controller.stop('clip complete');await flush();assert.equal(f.controller.state.pending,true);await f.advance(10000);assert.equal(f.controller.state.pending,false);assert.equal(signal.aborted,true);assert.match(f.controller.state.saveError,/upload timeout/);assert.equal(f.counts().publishes,1);});
await check('late old session callbacks cannot mutate the next capture',async()=>{const f=recorderFixture();f.controller.arm();f.controller.afterFrame();const old=f.instances[0];f.controller.stop('clip complete');await flush();assert.equal(f.controller.arm(),true);const id=f.controller.state.id;old.ondataavailable?.({data:new Blob(['late'])});old.onstop?.();await flush();assert.equal(f.controller.state.id,id);assert.equal(f.controller.state.status,'armed');assert.equal(f.controller.state.bytes,0);});
await check('byte budget interrupts and marks truncated',async()=>{const f=recorderFixture();f.controller.arm({byteLimit:3});f.controller.afterFrame();f.instances[0].ondataavailable({data:new Blob(['too-large'])});await flush();assert.equal(f.controller.state.truncated,true);assert.equal(f.controller.state.pending,false);assert.equal(f.stops[0],'capture byte limit');assert.equal(f.counts().uploads,0);});
await check('MP4 fallback keeps actual MIME metadata',async()=>{const f=recorderFixture({mime:'video/mp4'});f.controller.arm();f.controller.afterFrame();f.controller.stop('clip complete');await flush();assert.equal(f.controller.state.mime,'video/mp4');assert.equal(f.controller.state.artifact,'/capture.mp4');});
function benchmarkFixture({safe=true}={}){
 const dom=new JSDOM('<body><canvas></canvas></body>',{url:'http://fixture.invalid/'}),camera=new T.PerspectiveCamera();globalThis.document=dom.window.document;globalThis.location=dom.window.location;globalThis.addEventListener=dom.window.addEventListener.bind(dom.window);let active=0,time=60,pauses=0,resumes=0,streams=0;
 globalThis.MediaRecorder=class{static isTypeSupported(){return true;}constructor(){this.state='inactive';this.mimeType='video/webm';}start(){this.state='recording';}pause(){this.state='paused';}resume(){this.state='recording';}stop(){this.state='inactive';this.onstop?.();}};
 const canvas=document.querySelector('canvas');canvas.captureStream=()=>{streams++;return {getTracks:()=>[{stop(){}}]};};
 const state=()=>({build:{sourceHash:'fixture',assetsHash:'fixture'},position:camera.position.toArray(),quaternion:camera.quaternion.toArray(),drawSize:[1280,720],quality:'high',variant:'stable',terrain:{pending:false},vegetation:{pending:false,error:null},flow:{pending:false,error:null,exposure:{valid:true}},programErrors:0,clearance:1.75,exposure:1.35,skyCache:{ready:true},cpu:{},shadow:{},navigation:{},worldTime:time});
 const api=makeBenchmark({params:new URLSearchParams('benchmark=1'),camera,canvas,landmarks:[{id:'side-spring',name:'Fixture'}],go(){},stop(){},getState:state,auditSky(){},setWaterDebug(){},setReviewDpr(){},setShadow(){},getShadow:()=>true,setTime:t=>time=t,syncPose(){},navigationHeight:()=>0,navigateGround:(p,previous)=>{p.y=1.75;return {blocked:null,distance:Math.hypot(p.x-previous.x,p.z-previous.z)};},pauseScene:()=>pauses++,resumeScene:()=>{resumes++;return safe;},planRegion:()=>({passed:true,points:[[0,0],[605,0]],length:605,seconds:605/1.55}),now:()=>active,getWorldTime:()=>time});
 return {api,state,advance(ms){active+=ms;time=api.time;api.beforeFrame(ms);api.afterFrame(ms,state());},counts:()=>({pauses,resumes,streams}),button:()=>document.querySelector('#benchmark-motion-clip'),close(){api.cancel('fixture cleanup');dom.window.close();}};
}
await check('normal initialization does not record or resume',()=>{const f=benchmarkFixture();assert.equal(f.api.videoPending,false);assert.deepEqual(f.counts(),{pauses:0,resumes:0,streams:0});f.close();});
await check('explicit clip uses one safe resume and starts capture after a submitted frame',()=>{const f=benchmarkFixture();assert.ok(f.button());f.button().onclick();assert.equal(f.counts().resumes,1);assert.equal(f.counts().streams,0);f.advance(100);assert.equal(f.counts().streams,1);f.close();});
await check('safety guard refusal cancels clip and produces no recorder',()=>{const f=benchmarkFixture({safe:false});f.button().onclick();assert.equal(f.api.active,false);assert.equal(f.api.videoPending,false);assert.equal(f.counts().streams,0);assert.ok(f.api.visualRecords.some(r=>r.reason==='capture resume blocked'));f.close();});
await check('12 second clip preserves history and cannot claim full loop completion',async()=>{const f=benchmarkFixture();f.api.startRealtime();f.advance(100);f.api.cancel('prior failure');const prior=f.api.visualRecords[0];f.button().onclick();for(let i=0;i<120;i++)f.advance(100);await flush();assert.equal(f.api.active,false);assert.ok(f.counts().pauses>0);assert.equal(f.api.visualRecords[0],prior);const r=f.api.visualRecords.findLast(r=>r.kind==='motion-clip');assert.ok(r);assert.equal(r.completed,true);assert.equal(r.route.completed,false);assert.ok(r.route.progress<.04);assert.ok(r.worldSeconds>=12&&r.worldSeconds<12.11);assert.equal(r.evidenceReadbackFrames,0);assert.ok(Math.abs(r.endPosition[0]-18.6)<1e-8);f.close();});
await check('manual cancel retains samples and immediately pauses scene',()=>{const f=benchmarkFixture();f.button().onclick();f.advance(100);f.api.cancel('window-blur');assert.equal(f.api.active,false);assert.ok(f.counts().pauses>0);assert.equal(f.api.visualRecords.at(-1).samples.length,1);assert.equal(f.api.visualRecords.at(-1).reason,'window-blur');f.close();});
const result={schema:'review-capture-offline-v1',scope:'CPU/DOM mocks only, no browser/GPU/media measurement',passed:cases.every(c=>c.passed),cases};if(process.argv[2]){mkdirSync(dirname(resolve(process.argv[2])),{recursive:true});writeFileSync(process.argv[2],JSON.stringify(result,null,2)+'\n');}console.log(JSON.stringify({passed:result.passed,cases:cases.length,failed:cases.filter(c=>!c.passed)}));if(!result.passed)process.exitCode=1;
