// Written before implementation. Failure inventory:
// Phase 2 coverage regression (written before extent change): preserve legacy
// 280 m receiver coverage; 128 m probes lost live weight at 96–112 m.
// Narrowing a single map must not be sold as free quality.
// - Candidate changes map allocation, depth interval, or bias instead of scope.
// - Runtime A/B does not restore the original 280 m projection and fade.
// - Weight is based on viewer distance or a different matrix than the sampled map.
// - Invalid light-frustum depth keeps live weight, leaving a lit seam at the edge.
// - Ground combines cache*live, producing a darker value than either input.
// - Cache is stamped on trees/animals or other elevated receiving surfaces.
// - Shader declarations arrive after use, are duplicated, or patch point shadows.
// - Terrain keeps its separate 65–100 m direct-light multiplier in coherent mode.
// - Constructor claims exact alpha coverage although Three overrides it to 0.5.
// - Wind input/function diverges between colour and custom depth passes.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import * as T from 'three';
const cases=[];const check=(name,fn)=>{try{fn();cases.push({name,passed:true});}catch(error){cases.push({name,passed:false,error:String(error)});}};
let api;try{api=await import('../shadow-budget.js');}catch(error){cases.push({name:'bounded shadow implementation exists',passed:false,error:String(error)});}
if(api){
 const {shadowBudget,setShadowBudget,shadowLiveWeight,shadowVisibility,patchShadowChunk}=api;
 check('A/B modes preserve legacy receiver extent, map, bias and depth interval',()=>{const light=new T.DirectionalLight();light.shadow.mapSize.set(2048,2048);light.shadow.normalBias=.08;light.shadow.bias=-.00015;light.shadow.camera.near=1;light.shadow.camera.far=1200;const before={size:light.shadow.mapSize.toArray(),normal:light.shadow.normalBias,bias:light.shadow.bias,near:light.shadow.camera.near,far:light.shadow.camera.far};for(const enabled of [true,false,true,false]){setShadowBudget(light,enabled);assert.equal(light.shadow.camera.right-light.shadow.camera.left,280);assert.equal(light.shadow.camera.top-light.shadow.camera.bottom,280);assert.equal(shadowBudget.enabled.value,enabled?1:0);assert.deepEqual({size:light.shadow.mapSize.toArray(),normal:light.shadow.normalBias,bias:light.shadow.bias,near:light.shadow.camera.near,far:light.shadow.camera.far},before);}light.shadow.mapSize.set(512,512);setShadowBudget(light,true);assert.deepEqual(light.shadow.mapSize.toArray(),[512,512]);});
 check('sampled light-plane coordinates, corners and depth define the shared live mask',()=>{assert.equal(shadowLiveWeight([.5,.5,.5]),1);assert.equal(shadowLiveWeight([.82,.5,.5]),1);assert.equal(shadowLiveWeight([.99,.5,.5]),0);assert.equal(shadowLiveWeight([.5,.99,.5]),0);assert.equal(shadowLiveWeight([.99,.99,.5]),0);assert.equal(shadowLiveWeight([.5,.5,1.001]),0);assert.equal(shadowLiveWeight([1.01,.5,.5]),0);assert.equal(shadowLiveWeight([.5,.5,1]),1);assert.equal(shadowLiveWeight([.5,.5,-.01]),0);for(let i=0;i<100;i++){const x=.32+.17*i/99;assert.ok(Math.abs(shadowLiveWeight([.5+x,.5,.5])-shadowLiveWeight([.5,.5-x,.5]))<1e-12);}});
 check('handover is convex, continuous, raw-live at centre and cache at edge',()=>{for(const live of [0,.2,.8,1])for(const cached of [.28,.7,1]){let previous=live;for(let i=0;i<=100;i++){const coord=[.5+.5*i/100,.5,.5],value=shadowVisibility({enabled:true,ground:true,coord,live,cached});assert.ok(value>=Math.min(live,cached)-1e-12&&value<=Math.max(live,cached)+1e-12);assert.ok(Math.abs(value-previous)<.09);previous=value;}assert.equal(shadowVisibility({enabled:true,ground:true,coord:[.5,.5,.5],live,cached}),live);assert.equal(shadowVisibility({enabled:true,ground:true,coord:[.99,.5,.5],live,cached}),cached);}assert.equal(shadowVisibility({enabled:true,ground:true,coord:[.5,.5,1.1],live:.1,cached:.4}),.4);});
 check('non-ground receivers never inherit the cached ground footprint',()=>{for(const cached of [0,.28,1]){assert.equal(shadowVisibility({enabled:true,ground:false,coord:[.5,.5,.5],live:.25,cached}),.25);assert.equal(shadowVisibility({enabled:true,ground:false,coord:[.99,.5,.5],live:.25,cached}),1);}});
 check('legacy fade and intensity reproduce the original edge policy',()=>{for(const edge of [0,.32,.4,.49,.51]){const t=Math.min(1,Math.max(0,(edge-.32)/.17)),weight=1-t*t*(3-2*t);assert.ok(Math.abs(shadowVisibility({enabled:false,ground:true,coord:[.5+edge,.5,.5],live:.2,cached:.28,intensity:.8})-(1-.8*weight*.8))<1e-12);}assert.equal(shadowVisibility({enabled:false,coord:[.5,.5,1.1],live:0}),1);});
 check('three actual projected-shadow returns share one wrapper; point variants stay intact',()=>{const raw=T.ShaderChunk.shadowmap_pars_fragment,out=patchShadowChunk(raw),point=raw.indexOf('#if NUM_POINT_LIGHT_SHADOWS > 0',raw.indexOf('float getShadow('));assert.equal((out.match(/return islandShadowVisibility\(/g)||[]).length,3);assert.equal((out.match(/shadowCoord\.xyz \/= shadowCoord\.w;/g)||[]).length,3);assert.equal(out.slice(out.indexOf('#if NUM_POINT_LIGHT_SHADOWS > 0',out.indexOf('float getShadow('))),raw.slice(point));assert.match(out,/sampler2DShadow shadowMap/);assert.match(out,/shadowCoord\.z <= 1\.0/);assert.doesNotMatch(out,/shadowIntensity \*= 1\.-smoothstep/);});
 const {makeAtmosphere}=await import('../atmosphere.js');
 check('assembled standard-material shader declares airWorld before common shadow helper once',()=>{const material=new T.MeshStandardMaterial(),object=new T.Mesh(new T.BoxGeometry(),material);makeAtmosphere({}).apply(object);const s={uniforms:{},vertexShader:T.ShaderLib.standard.vertexShader,fragmentShader:T.ShaderLib.standard.fragmentShader};material.onBeforeCompile(s);assert.equal(s.uniforms.shadowBudgetEnabled,shadowBudget.enabled);assert.equal((s.fragmentShader.match(/varying vec3 airWorld;/g)||[]).length,1);assert.equal((s.fragmentShader.match(/float islandShadowVisibility\(/g)||[]).length,1);assert.ok(s.fragmentShader.indexOf('varying vec3 airWorld;')<s.fragmentShader.indexOf('float islandShadowVisibility('));assert.equal((s.fragmentShader.match(/return islandShadowVisibility\(/g)||[]).length,3);assert.match(s.fragmentShader,/#ifdef ISLAND_SHADOW_GROUND/);assert.match(s.fragmentShader,/mix\(cachedVisibility, shadow, liveWeight\)/);});
 check('ground alone opts into cached handover and legacy multiplier is runtime gated',()=>{const source=readFileSync(new URL('../world.js',import.meta.url),'utf8');assert.match(source,/m\.defines[^\n]*ISLAND_SHADOW_GROUND/);assert.match(source,/if\(shadowBudgetEnabled<\.5\)reflectedLight\.directDiffuse\*=mix\(1\.,mix\(\.28,1\.,canopy\.r\),smoothstep\(65\.,100\.,viewDistance\)\)/);});
 check('wind stays shared while depth constructor tracks actual instance alpha and renderer approximation is explicit',()=>{const source=readFileSync(new URL('../props.js',import.meta.url),'utf8'),renderer=readFileSync(new URL('../../../node_modules/three/src/renderers/webgl/WebGLShadowMap.js',import.meta.url),'utf8');assert.match(source,/map:mesh\.material\.map,alphaTest:mesh\.material\.alphaTest/);assert.match(source,/transformed\+=treeWindOffset\(position,root,leafMotion,mat3\(modelMatrix\*instanceMatrix\)\)/);assert.match(source,/transformed\+=treeWindOffset\(position,treeRoot,leafMotion,mat3\(modelMatrix\*instanceMatrix\)\)/);assert.match(renderer,/result\.alphaTest = \( material\.alphaToCoverage === true \) \? 0\.5 : material\.alphaTest/);});
}
const result={schema:'island-shadow-budget-offline-v1',scope:'projection, visibility mathematics and shader integration contracts; GPU compilation/visual/performance acceptance belongs to headed review',cases,passed:cases.length>1&&cases.every(c=>c.passed)};
if(process.argv[2]){const path=resolve(process.argv[2]);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify(result,null,2)+'\n');}
console.log(JSON.stringify({passed:result.passed,cases:cases.length,failed:cases.filter(c=>!c.passed)}));if(!result.passed)process.exitCode=1;
