import {createHash} from 'node:crypto';import {readFileSync,readdirSync} from 'node:fs';
const sourceRoot=new URL('.',import.meta.url);const hash=createHash('sha256');for(const name of [...readdirSync(sourceRoot).filter(n=>/\.(js|css|html)$/.test(n)), '../../src/flight-experience/world.ts', '../../src/flight-experience/environment/cloud-shared.glsl.ts', '../../package-lock.json'].sort()){hash.update(name);hash.update(readFileSync(new URL(name,sourceRoot)))}const sourceHash=hash.digest('hex');
const assetHash=createHash('sha256');for(const name of readdirSync(new URL('public/assets/',sourceRoot)).sort()){const p=new URL(`public/assets/${name}`,sourceRoot);if((await import('node:fs')).statSync(p).isFile()){assetHash.update(name);assetHash.update(readFileSync(p))}}const assetsHash=assetHash.digest('hex');
import {build} from 'vite';import{fileURLToPath}from'node:url';await build({configFile:false,define:{__WORLD_BUILD__:JSON.stringify({baseline:'f0092ff87a9372342f168c20ec7f52a6b165b8bb',sourceHash,assetsHash})},root:fileURLToPath(new URL('.',import.meta.url)),base:'./',worker:{format:'es'},build:{outDir:process.argv.includes('--publish')?'../river-realism/dist':'.review-dist',emptyOutDir:true,assetsInlineLimit:0,chunkSizeWarningLimit:950}})
// Serve only the assets the accepted scene uses; all rejected experiments stay private.
const {readdir,rm}=await import('node:fs/promises');
const out=fileURLToPath(new URL(`${process.argv.includes('--publish')?'../river-realism/dist':'.review-dist'}/assets/`,import.meta.url));
const keep=new Set(['needle-spray-v1.png','fir-bark-albedo.webp','fir-bark-normal.webp','fir-bark-rough.webp','surf-lace.bin','cloud-volume.bin','terrain-cover.bin','terrain-horizon.bin','coast-height-r9.bin','fir-a-spatial-near-lite.glb','terrain-ao.bin','terrain-sun.bin','apatosaurus.glb','meadow-grass.glb','pine-b-atlas.webp','scanned-props.glb','fir-a-atlas.webp','fir-a-spatial-near-layered.glb','cloud-weather.bin','river-ripples.png',...['cliff','ganges_river_pebbles','rocky_terrain_02','leafy_grass','sandy_gravel_02'].flatMap(n=>['albedo','normal','arm'].map(c=>`${n}-${c}.webp`))]);
for(const name of await readdir(out))if(!keep.has(name)&&!name.endsWith('.js')&&!name.endsWith('.css'))await rm(`${out}/${name}`,{force:true,recursive:true});
