import {copyFileSync,existsSync,writeFileSync} from 'node:fs';
const animalModels=['apatosaurus','triceratops'];
for(const id of animalModels){const source=new URL(`../../src/content/animals/${id}/model/model.glb`,import.meta.url);if(!existsSync(source))throw Error('Missing museum model '+id);copyFileSync(source,new URL(`public/assets/${id}.glb`,import.meta.url));}
import {createHash} from 'node:crypto';import {readFileSync,readdirSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
const sourceRoot=new URL('.',import.meta.url);const hash=createHash('sha256');for(const name of [...readdirSync(sourceRoot).filter(n=>/\.(js|css|html)$/.test(n)), '../../src/flight-experience/world.ts', '../../src/flight-experience/environment/cloud-shared.glsl.ts', '../../package-lock.json'].sort()){hash.update(name);hash.update(readFileSync(new URL(name,sourceRoot)))}const sourceHash=hash.digest('hex');
const animalResources=animalModels.map(id=>{const data=readFileSync(new URL(`public/assets/${id}.glb`,import.meta.url)),json=JSON.parse(data.subarray(20,20+data.readUInt32LE(12)).toString());return{id,source:`src/content/animals/${id}/model/model.glb`,url:`assets/${id}.glb`,bytes:data.length,sha256:createHash('sha256').update(data).digest('hex'),animations:(json.animations??[]).map(a=>a.name),materials:json.materials?.length??0,images:json.images?.length??0};});writeFileSync(new URL('public/assets/animal-resources.json',import.meta.url),JSON.stringify({schema:'island-animal-resources-v1',animals:animalResources},null,2));
const assetHash=createHash('sha256');for(const name of readdirSync(new URL('public/assets/',sourceRoot)).sort()){const p=new URL(`public/assets/${name}`,sourceRoot);if((await import('node:fs')).statSync(p).isFile()){assetHash.update(name);assetHash.update(readFileSync(p))}}const assetsHash=assetHash.digest('hex');
const commit=execFileSync('git',['rev-parse','HEAD'],{cwd:sourceRoot,encoding:'utf8'}).trim(),dirty=execFileSync('git',['status','--porcelain'],{cwd:sourceRoot,encoding:'utf8'}).trim().length>0;
import {build} from 'vite';import{fileURLToPath}from'node:url';await build({configFile:false,define:{__WORLD_BUILD__:JSON.stringify({commit,dirty,sourceHash,assetsHash})},root:fileURLToPath(new URL('.',import.meta.url)),base:'./',worker:{format:'es'},build:{outDir:process.argv.includes('--publish')?'../river-realism/dist':'.review-dist',emptyOutDir:true,assetsInlineLimit:0,chunkSizeWarningLimit:950}})
// Serve only the assets the accepted scene uses; all rejected experiments stay private.
const {readdir,rm}=await import('node:fs/promises');
const out=fileURLToPath(new URL(`${process.argv.includes('--publish')?'../river-realism/dist':'.review-dist'}/assets/`,import.meta.url));
const keep=new Set(['needle-spray-v1.png','fir-bark-albedo.webp','fir-bark-normal.webp','fir-bark-rough.webp','surf-lace.bin','cloud-volume.bin','terrain-cover.bin','terrain-horizon.bin','coast-height-r9.bin','fir-a-spatial-near-lite.glb','terrain-ao.bin','terrain-sun.bin','apatosaurus.glb','triceratops.glb','animal-resources.json','meadow-grass.glb','pine-b-atlas.webp','scanned-props.glb','fir-a-atlas.webp','fir-a-spatial-near-layered.glb','cloud-weather.bin','river-ripples.png',...['cliff','ganges_river_pebbles','rocky_terrain_02','leafy_grass','sandy_gravel_02'].flatMap(n=>['albedo','normal','arm'].map(c=>`${n}-${c}.webp`))]);
for(const name of await readdir(out))if(!keep.has(name)&&!name.endsWith('.js')&&!name.endsWith('.css'))await rm(`${out}/${name}`,{force:true,recursive:true});

writeFileSync(new URL(`${process.argv.includes('--publish')?'../river-realism/dist':'.review-dist'}/build-meta.json`,import.meta.url),JSON.stringify({commit,dirty,sourceHash,assetsHash,dependencies:{three:JSON.parse(readFileSync(new URL('../../node_modules/three/package.json',import.meta.url))).version,vite:JSON.parse(readFileSync(new URL('../../node_modules/vite/package.json',import.meta.url))).version}},null,2));
