import './style.css'
import * as T from 'three'
import{makeSky}from'./sky.js'
import{SIZE,terrainHeight,surfaceHeight,waterLevelAt,makeLandscape,groundMaterial,landmarks,smooth,biomeAt}from'./world.js'
import{makeProps,riverRocks}from'./props.js'
import{makeWater}from'./water.js'
import{makeCliffs}from'./hero-crags.js'
import{makeAtmosphere}from'./atmosphere.js'
const $=s=>document.querySelector(s),params=new URLSearchParams(location.search)
let fine=params.get('quality')==='high',cruise=false,touring=false,tourT=0,speedIndex=1,yaw=0,pitch=0,elapsed=0,last=0,frames=[],frame=0
const speeds=[5,35,150],speedNames=['近看','漫游','远行']
const renderer=new T.WebGLRenderer({canvas:$('#scene'),antialias:false,powerPreference:'high-performance'});renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.info.autoReset=false
const scene=new T.Scene();scene.background=new T.Color('#c8dce2');const camera=new T.PerspectiveCamera(62,innerWidth/innerHeight,.3,45000);camera.rotation.order='YXZ'
const sunDirection=new T.Vector3(-.55,.72,.31).normalize();
const sun=new T.DirectionalLight('#fff1d9',2.35);sun.castShadow=true;sun.shadow.mapSize.set(512,512);Object.assign(sun.shadow.camera,{left:-140,right:140,top:140,bottom:-140,near:1,far:1200});sun.shadow.bias=-.00015;sun.shadow.normalBias=.08;scene.add(sun,sun.target);scene.add(new T.HemisphereLight('#d7e9f4','#45533e',.85))
const sky=await makeSky(sunDirection);const skyScene=new T.Scene();skyScene.add(sky.mesh);const pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(skyScene,.03,.3,45000).texture;scene.environmentIntensity=.42;pmrem.dispose();scene.add(sky.mesh);scene.background=null;
const air=makeAtmosphere(sky.uniforms);
const landscape=makeLandscape(await groundMaterial(),o=>air.apply(o),()=>fine);scene.add(landscape.group);air.apply(landscape.group)
const water=makeWater(renderer,camera,riverRocks,sky.uniforms,()=>fine)
$('#load-detail').textContent='铺开森林、岩岸和潮汐河谷…'
const props=await makeProps(renderer,o=>air.apply(o),()=>fine);scene.add(props.group);air.apply(props.group);const cliffs=await makeCliffs();scene.add(cliffs);air.apply(cliffs)
const mapBase=document.createElement('canvas');mapBase.width=mapBase.height=400;const baseCtx=mapBase.getContext('2d'),pixels=baseCtx.createImageData(400,400),seaDepth=new Uint8Array(400*400)
for(let z=0;z<400;z++)for(let x=0;x<400;x++){const wx=(x/399-.5)*SIZE,wz=(z/399-.5)*SIZE,h=terrainHeight(wx,wz),wl=waterLevelAt(wx,wz),i=(z*400+x)*4;seaDepth[z*400+x]=Math.max(0,Math.min(255,(-.7-h)/40*255));let c;if(h<wl){const shallow=1-smooth(wl-14,wl,h);c=[55+shallow*4,121-shallow*32,133-shallow*24]}else if(biomeAt(wx,wz).marsh>.4)c=[123,123,75];else if(biomeAt(wx,wz).grass>.35)c=[155,161,76];else if(h<8)c=[194,192,150];else if(h<160)c=[66+h*.18,100+h*.14,68+h*.13];else c=[107+h*.17,121+h*.15,99+h*.16];pixels.data.set([...c,255],i)}baseCtx.putImageData(pixels,0,0);water.setTerrainDepth(seaDepth,400,SIZE)
function map(canvas,labels=false){const c=canvas.getContext('2d'),size=canvas.width;c.drawImage(mapBase,0,0,size,size);c.font=`${labels?13:10}px system-ui`;for(let i=0;i<landmarks.length;i++){const l=landmarks[i],x=(l.p[0]/SIZE+.5)*size,y=(l.p[2]/SIZE+.5)*size;c.fillStyle='#f5ecc8';c.beginPath();c.arc(x,y,labels?9:4,0,6.28);c.fill();if(labels){c.fillStyle='#274d3a';c.textAlign='center';c.fillText(i+1,x,y+4)}}const x=(camera.position.x/SIZE+.5)*size,y=(camera.position.z/SIZE+.5)*size;c.save();c.translate(x,y);c.rotate(-yaw);c.fillStyle='#fff';c.strokeStyle='#173e39';c.lineWidth=2;c.beginPath();c.moveTo(0,-8);c.lineTo(-5,5);c.lineTo(5,5);c.closePath();c.fill();c.stroke();c.restore()}
function orient(target){camera.lookAt(target);yaw=camera.rotation.y;pitch=camera.rotation.x}
function stop(){touring=false;cruise=false;$('#tour').textContent='环岛导览';$('#tour').setAttribute('aria-pressed','false');$('#cruise').textContent='向前巡航';$('#cruise').setAttribute('aria-pressed','false');document.body.classList.remove('touring')}
function go(id){const l=landmarks.find(p=>p.id===id)??landmarks[0];stop();camera.position.fromArray(l.p);camera.position.y=Math.max(camera.position.y,surfaceHeight(camera.position.x,camera.position.z)+3);orient(new T.Vector3(...l.t));$('#place').textContent=l.name;$('#place-note').textContent=l.note;history.replaceState(null,'',`?place=${l.id}&quality=${fine?'high':'mobile'}`);map($('#minimap'));frames=[]}
for(const [i,l]of landmarks.entries()){const b=document.createElement('button');b.innerHTML=`${i+1} · ${l.name}<small>${l.note}</small>`;b.onclick=()=>{go(l.id);$('#map-dialog').close()};$('#destinations').append(b)}
$('#map-button').onclick=()=>{stop();map($('#large-map'),true);$('#map-dialog').showModal()};$('#map-dialog .close').onclick=()=>$('#map-dialog').close();$('#help').onclick=()=>{stop();$('#help-dialog').showModal()};$('#help-dialog .close').onclick=()=>$('#help-dialog').close()
let mobileScale=1,renderScale=1;function quality(){const budget=fine?2400000:1300000;renderer.setPixelRatio(Math.min(devicePixelRatio,fine?1.6:mobileScale,Math.sqrt(budget/(innerWidth*innerHeight)))*renderScale);renderer.setSize(innerWidth,innerHeight,false);$('#quality').textContent=fine?'精细画质':'手机画质';const size=fine?2048:512;if(sun.shadow.mapSize.x!==size){sun.shadow.map?.dispose();sun.shadow.map=null;sun.shadow.mapSize.set(size,size)}}
$('#quality').onclick=()=>{fine=!fine;renderScale=1;quality()};addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();quality()})
$('#speed').onclick=()=>{speedIndex=(speedIndex+1)%3;$('#speed').textContent=`速度 · ${speedNames[speedIndex]}`}
$('#cruise').onclick=()=>{const next=!cruise;stop();cruise=next;$('#cruise').textContent=cruise?'停止巡航':'向前巡航';$('#cruise').setAttribute('aria-pressed',String(cruise))}
const route=new T.CatmullRomCurve3([[-1850,45,-450],[-1750,90,-1100],[-2020,260,-2250],[-1650,420,-3350],[800,650,-2500],[1800,710,-5850],[5500,390,-700],[6500,270,2100],[8400,150,3300],[4600,130,5300],[2950,130,6200],[500,330,4200],[-2100,270,3450],[-3100,200,500],[-3000,230,-2400],[-1850,80,-450]].map(p=>new T.Vector3(...p)),false,'centripetal')
const tourGaze=new T.CatmullRomCurve3([[-1920,20,-650],[-1880,30,-1350],[-1850,130,-2600],[-1800,70,-2600],[700,390,-2700],[-1500,150,100],[4700,15,1400],[-800,200,1400],[-2300,5,2850],[-2100,80,100],[-2150,170,-2200],[-1900,20,-800]].map(p=>new T.Vector3(...p)),false,'centripetal')
const safeRoute=new T.CatmullRomCurve3(Array.from({length:241},(_,i)=>{const p=route.getPoint(i/240);let floor=surfaceHeight(p.x,p.z);for(const [dx,dz] of [[-200,0],[200,0],[0,-200],[0,200]])floor=Math.max(floor,surfaceHeight(p.x+dx,p.z+dz));p.y=Math.max(p.y,floor+110);return p}),false,'centripetal')
$('#tour').onclick=()=>{const next=!touring;stop();if(next){touring=true;tourT=0;$('#tour').textContent='停止导览';$('#tour').setAttribute('aria-pressed','true');document.body.classList.add('touring')}}
const keys=new Set(),joy={x:0,y:0},alt={up:false,down:false};let look=null
function manual(){if(touring)stop()}
addEventListener('keydown',e=>{if(e.target.closest('input,textarea,dialog'))return;if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ShiftLeft','ShiftRight','Space'].includes(e.code)){e.preventDefault();if(e.code==='Space')stop();else{manual();keys.add(e.code)}}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();joy.x=joy.y=0;alt.up=alt.down=false;look=null;stop();$('#stick').style.transform=''})
renderer.domElement.addEventListener('pointerdown',e=>{manual();look={id:e.pointerId,x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId)})
renderer.domElement.addEventListener('pointermove',e=>{if(!look||look.id!==e.pointerId)return;yaw-=(e.clientX-look.x)*.004;pitch=T.MathUtils.clamp(pitch-(e.clientY-look.y)*.003,-1.35,1.35);look.x=e.clientX;look.y=e.clientY;camera.rotation.set(pitch,yaw,0)})
renderer.domElement.addEventListener('pointerup',()=>look=null);renderer.domElement.addEventListener('pointercancel',()=>look=null)
const stick=$('#joystick');function moveStick(e){const r=stick.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/(r.width*.36),y=(e.clientY-r.top-r.height/2)/(r.height*.36),len=Math.max(1,Math.hypot(x,y));joy.x=x/len;joy.y=y/len;$('#stick').style.transform=`translate(${joy.x*r.width*.30}px,${joy.y*r.height*.30}px)`}
stick.onpointerdown=e=>{manual();stick.setPointerCapture(e.pointerId);moveStick(e)};stick.onpointermove=e=>{if(stick.hasPointerCapture(e.pointerId))moveStick(e)};stick.onpointerup=stick.onpointercancel=()=>{joy.x=joy.y=0;$('#stick').style.transform=''}
for(const id of ['up','down']){const b=$('#'+id);b.onpointerdown=e=>{manual();alt[id]=true;b.setPointerCapture(e.pointerId)};b.onpointerup=b.onpointercancel=()=>alt[id]=false;b.onclick=()=>{manual();camera.position.y+=id==='up'?4:-4}}
quality();go(params.get('place')??'forest');if(params.has('pose')){const p=params.get('pose').split(',').map(Number);if(p.length===5&&p.every(Number.isFinite)){camera.position.set(p[0],p[1],p[2]);yaw=p[3];pitch=p[4];camera.rotation.set(pitch,yaw,0)}};props.update(camera);landscape.update(camera);$('#load-detail').textContent='准备阳光、海面与远景…';await landscape.ready;await renderer.compileAsync(scene,camera);$('#loading').classList.add('done');$('#loading').setAttribute('aria-hidden','true');document.body.dataset.ready='true'
let perfStage={propsMs:0,renderMs:0},longFrames=0;
let lost=false;renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();lost=true;$('#loading').classList.remove('done');$('#load-detail').textContent='图形资源中断，请刷新重试。'})
function render(t){requestAnimationFrame(render);if(lost||document.hidden){last=t;return}const raw=last?t-last:16;const dt=Math.min(.05,raw/1000);last=t;elapsed+=dt;frames.push(raw);if(raw>50)longFrames++;if(frames.length>120)frames.shift()
 if(touring){tourT=Math.min(1,tourT+dt/320);const p=safeRoute.getPoint(tourT),target=tourT<.986?safeRoute.getPoint(tourT+.014):tourGaze.getPoint(1);p.y=Math.max(p.y,surfaceHeight(p.x,p.z)+90);target.y=Math.max(target.y-35,p.y-120);camera.position.copy(p);orient(target);pitch=T.MathUtils.clamp(pitch,-.45,.25);camera.rotation.set(pitch,yaw,0);if(tourT>=1)stop()}
 else{const f=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)-joy.y+(cruise?1:0),r=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+joy.x,u=(keys.has('KeyE')||alt.up?1:0)-(keys.has('KeyQ')||alt.down?1:0),boost=keys.has('ShiftLeft')||keys.has('ShiftRight')?2:1,v=speeds[speedIndex]*boost*dt,len=Math.max(1,Math.hypot(f,r));camera.position.x+=(-Math.sin(yaw)*f+Math.cos(yaw)*r)*v/len;camera.position.z+=(-Math.cos(yaw)*f-Math.sin(yaw)*r)*v/len;camera.position.y+=u*v*.7;camera.rotation.set(pitch,yaw,0)}
 camera.position.y=T.MathUtils.clamp(camera.position.y,surfaceHeight(camera.position.x,camera.position.z)+3,2100)
 const sx=Math.round(camera.position.x/8)*8,sz=Math.round(camera.position.z/8)*8,sy=Math.max(0,terrainHeight(sx,sz));sun.target.position.set(sx,sy,sz);sun.position.copy(sunDirection).multiplyScalar(650).add(sun.target.position)
 sky.update(elapsed);const ps=performance.now();props.update(camera);landscape.update(camera);perfStage.propsMs=performance.now()-ps;renderer.info.reset();const rs=performance.now();params.has('dry')?renderer.render(scene,camera):water.render(scene,camera,elapsed);perfStage.renderMs=performance.now()-rs
 if(frame++%30===0){let nearest=landmarks[0],dist=Infinity;for(const l of landmarks){const d=Math.hypot(l.p[0]-camera.position.x,l.p[2]-camera.position.z);if(d<dist){nearest=l;dist=d}}$('#place').textContent=dist>6500?'外海':nearest.name;$('#place-note').textContent=touring?'沿海岸、河谷和山脊连续飞行':dist>6500?'打开地图，随时返回海岛':nearest.note;const avg=frames.reduce((a,b)=>a+b,0)/frames.length;$('#status').textContent=`海拔 ${Math.round(camera.position.y)} m · ${Math.round(1000/avg)} fps${touring?' · 导览中':''}`;const ordered=[...frames].sort((a,b)=>a-b);const metrics={waterTime:elapsed,frameMs:{p50:ordered[Math.floor(ordered.length*.5)],p95:ordered[Math.floor(ordered.length*.95)],max:ordered.at(-1)},longFrames,cpu:perfStage,drawSize:[renderer.domElement.width,renderer.domElement.height],version:'island-r4.7',position:camera.position.toArray(),ground:terrainHeight(camera.position.x,camera.position.z),touring,tourT,cruise,speed:speeds[speedIndex],quality:fine?'high':'mobile',pixelRatio:renderer.getPixelRatio(),viewport:[innerWidth,innerHeight],fps:1000/avg,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,objects:props.counts,terrain:landscape.status()};$('#status').dataset.metrics=JSON.stringify(metrics);map($('#minimap'));if(frames.length===120&&frame>240&&frame%240===1&&ordered[Math.floor(ordered.length*.95)]>25&&avg>20&&renderScale>.7){renderScale=Math.max(.7,renderScale-.1);quality();frames=[]}}
}
requestAnimationFrame(render)
